# Generated by Django 3.2 on 2021-06-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=50)),
                ('apellido_personal', models.CharField(max_length=50)),
                ('dni_personal', models.CharField(max_length=15)),
                ('telefono_personal', models.CharField(max_length=15)),
                ('fecha_nacimiento_personal', models.DateField()),
                ('lugar_nacimiento_personal', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_permiso', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('horario_salida', models.DateTimeField()),
                ('horario_regreso', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_laboral', models.CharField(max_length=255)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('area', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=255)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
    ]
