# Generated by Django 3.2.8 on 2022-02-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210916_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia_personal',
            name='hora_ingreso',
        ),
        migrations.RemoveField(
            model_name='asistencia_personal',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='asistencia_personal',
            name='fecha_asistencia_personal',
            field=models.DateTimeField(null=True),
        ),
    ]
