# Generated by Django 3.2.8 on 2022-02-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20220227_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_personal',
            name='fecha_asistencia_personal',
            field=models.DateField(null=True),
        ),
    ]
