# Generated by Django 3.2 on 2021-10-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=50)),
                ('horarios', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganancia', models.CharField(max_length=50)),
                ('observacion_ventas', models.CharField(max_length=100)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion_Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produccion', models.CharField(max_length=50)),
                ('fecha_produccion', models.CharField(max_length=50)),
                ('materiales', models.CharField(max_length=50)),
                ('costo_venta', models.CharField(max_length=50)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Materiales_Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumos_disponibles', models.CharField(max_length=100)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Informe_Cuatrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_cuatrimestrales', models.CharField(max_length=100)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Compras_Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumos', models.CharField(max_length=50)),
                ('observaciones_compra', models.CharField(max_length=100)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
        ),
    ]
