# Generated by Django 3.2.8 on 2021-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion_taller',
            name='fecha_produccion',
            field=models.DateField(),
        ),
    ]
