# Generated by Django 3.2.8 on 2021-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_alter_produccion_taller_fecha_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_taller',
            name='materiales_fin_ciclo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
