# Generated by Django 3.2.8 on 2021-12-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_alumnoxtaller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumnoxTaller',
        ),
    ]
