# Generated by Django 3.2.8 on 2021-12-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210916_1801'),
        ('taller', '0006_taller_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='personals',
            field=models.ManyToManyField(to='personal.Personal'),
        ),
    ]
