# Generated by Django 3.2.8 on 2021-12-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_taller_personals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taller',
            old_name='alumnos',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='taller',
            old_name='personals',
            new_name='personal',
        ),
    ]
