# Generated by Django 3.2.8 on 2021-12-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('personal', '0002_auto_20210916_1801'),
        ('taller', '0010_auto_20211227_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='alumno',
            field=models.ManyToManyField(to='alumno.Alumno', verbose_name='alumnos'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='personal',
            field=models.ManyToManyField(to='personal.Personal', verbose_name='personals'),
        ),
    ]
