# Generated by Django 3.2.8 on 2021-12-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_auto_20211229_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='personal',
        ),
    ]
