# Generated by Django 3.2.8 on 2021-12-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('personal', '0002_auto_20210916_1801'),
        ('taller', '0012_auto_20211230_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='alumno_id',
            field=models.ManyToManyField(to='alumno.Alumno'),
        ),
        migrations.AddField(
            model_name='taller',
            name='personal_id',
            field=models.ManyToManyField(to='personal.Personal'),
        ),
    ]
