# Generated by Django 3.2.8 on 2021-12-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_auto_20211230_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taller',
            old_name='alumno_id',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='taller',
            old_name='personal_id',
            new_name='personal',
        ),
    ]
