# Generated by Django 3.2.8 on 2021-12-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0014_auto_20211230_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taller',
            old_name='alumno',
            new_name='alumno_id',
        ),
        migrations.RenameField(
            model_name='taller',
            old_name='personal',
            new_name='personal_id',
        ),
    ]
