# Generated by Django 3.2.8 on 2021-12-31 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210916_1801'),
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('taller', '0015_auto_20211230_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='alumno_id',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='personal_id',
        ),
        migrations.CreateModel(
            name='TallerAlumnoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('personal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
    ]
