# Generated by Django 3.2.8 on 2021-12-31 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210916_1801'),
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('taller', '0016_auto_20211231_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='alumno_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno'),
        ),
        migrations.AddField(
            model_name='taller',
            name='personal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.DeleteModel(
            name='TallerAlumnoPersonal',
        ),
    ]
