# Generated by Django 3.2.8 on 2021-12-31 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('personal', '0002_auto_20210916_1801'),
        ('taller', '0017_auto_20211231_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='alumno_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='personal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
    ]
