# Generated by Django 3.2.8 on 2021-12-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0018_auto_20211231_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='personal_id',
        ),
    ]
