# Generated by Django 3.2.8 on 2021-12-31 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('taller', '0022_remove_taller_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno'),
            preserve_default=False,
        ),
    ]
