# Generated by Django 3.2.8 on 2021-12-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210916_1801'),
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('taller', '0024_remove_taller_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='alumnos_id',
            field=models.ManyToManyField(to='alumno.Alumno'),
        ),
        migrations.AddField(
            model_name='taller',
            name='personal_id',
            field=models.ManyToManyField(to='personal.Personal'),
        ),
    ]
