# Generated by Django 3.2.8 on 2022-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('personal', '0002_auto_20210916_1801'),
        ('taller', '0026_auto_20220102_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='alumnos_id',
        ),
        migrations.AddField(
            model_name='taller',
            name='alumno_id',
            field=models.ManyToManyField(to='alumno.Alumno'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='personal_id',
            field=models.ManyToManyField(to='personal.Personal'),
        ),
    ]
