# Generated by Django 3.2.8 on 2022-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0028_auto_20220228_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras_taller',
            name='total',
            field=models.CharField(default=1500, max_length=10),
            preserve_default=False,
        ),
    ]
