# Generated by Django 3.2.8 on 2022-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0029_compras_taller_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion_taller',
            name='cantidad',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
