# Generated by Django 3.2.8 on 2022-03-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0030_produccion_taller_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales_taller',
            name='cantidad',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
