# Generated by Django 3.2.8 on 2022-03-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0031_materiales_taller_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_taller',
            name='producto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
