# Generated by Django 3.2.8 on 2022-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0032_ventas_taller_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_taller',
            name='cantidad_producto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
