# Generated by Django 3.2.8 on 2022-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0033_ventas_taller_cantidad_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas_taller',
            name='ganancia',
            field=models.IntegerField(max_length=50),
        ),
    ]
