# Generated by Django 3.2.8 on 2022-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0035_alter_compras_taller_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_taller',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventas_taller',
            name='ganancia',
            field=models.IntegerField(),
        ),
    ]
