# Generated by Django 3.2.8 on 2022-01-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_auto_20210916_1801'),
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('taller', '0027_auto_20220102_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompañante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_acompañante', models.CharField(max_length=300)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
        ),
    ]
