# Generated by Django 3.2.8 on 2022-01-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompañantes', '0002_remove_acompañante_taller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompañante',
            old_name='alumno',
            new_name='alumno_id',
        ),
        migrations.RenameField(
            model_name='acompañante',
            old_name='personal',
            new_name='personal_id',
        ),
    ]
