# Generated by Django 3.2.8 on 2022-01-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompañantes', '0003_auto_20220110_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompañante',
            old_name='alumno_id',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='acompañante',
            old_name='personal_id',
            new_name='personal',
        ),
    ]
