# Generated by Django 3.2 on 2021-04-11 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('apellido_alumno', models.CharField(max_length=50)),
                ('dni_alumno', models.CharField(max_length=15)),
                ('telefono_alumno', models.CharField(max_length=15, null=True)),
                ('fecha_nacimiento_alumno', models.DateField(null=True)),
                ('lugar_nacimiento_alumno', models.CharField(max_length=50)),
                ('direccion_alumno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedente_Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(max_length=20)),
                ('factor_rh', models.CharField(max_length=2)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patologia', models.CharField(max_length=50)),
                ('medicacion', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=255)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.alumno')),
                ('id_antecedente_medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.antecedente_medico')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=255)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Adicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jubilacion', models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=2, null=True)),
                ('pension', models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=2, null=True)),
                ('cobertura_social', models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=2, null=True)),
                ('certificado_discapacidad', models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=2, null=True)),
                ('vigencia_cerificado', models.DateField(null=True)),
                ('nivel_educacional', models.CharField(max_length=100, null=True)),
                ('grupo_familiar_convivencia', models.CharField(max_length=255, null=True)),
                ('actividades_realiza', models.CharField(max_length=255, null=True)),
                ('trabajo_madre', models.CharField(max_length=100, null=True)),
                ('trabajo_padre', models.CharField(max_length=100, null=True)),
                ('telefono_madre', models.CharField(max_length=20, null=True)),
                ('telefono_padre', models.CharField(max_length=20, null=True)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateTimeField()),
                ('estado_asistencia', models.CharField(max_length=20)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Acta_Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=100)),
                ('ingreso', models.TimeField()),
                ('salida', models.TimeField()),
                ('traslado', models.CharField(max_length=100)),
                ('personas_autorizadas_retiro', models.CharField(max_length=100)),
                ('dni_persona_autorizada', models.CharField(max_length=50)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumno.alumno')),
            ],
        ),
    ]
