# Generated by Django 3.2 on 2021-04-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_adicionales',
            old_name='vigencia_cerificado',
            new_name='vigencia_certificado',
        ),
    ]
