# Generated by Django 3.2 on 2021-04-27 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_alter_datos_adicionales_id_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_adicionales',
            name='id_alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno'),
        ),
    ]
