# Generated by Django 3.2 on 2021-04-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0006_alter_datos_adicionales_id_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_adicionales',
            old_name='id_alumno',
            new_name='alumno',
        ),
    ]
