# Generated by Django 3.2 on 2021-04-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0008_alter_datos_adicionales_jubilacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_adicionales',
            name='jubilacion',
            field=models.BooleanField(choices=[('si', 'si'), ('no', 'no')], max_length=2, null=True),
        ),
    ]
