# Generated by Django 3.2 on 2021-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0010_alter_datos_adicionales_jubilacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_adicionales',
            name='jubilacion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
