# Generated by Django 3.2 on 2021-04-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0012_alter_datos_adicionales_jubilacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acta_compromiso',
            old_name='id_alumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='antecedente_medico',
            old_name='id_alumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='asistencia_alumno',
            old_name='id_alumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='enfermeria',
            old_name='id_alumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='patologia',
            old_name='id_alumno',
            new_name='alumno',
        ),
    ]
