# Generated by Django 3.2 on 2021-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0013_auto_20210429_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_alumno',
            name='fecha_asistencia',
            field=models.DateField(),
        ),
    ]
