# Generated by Django 3.2 on 2021-05-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0014_alter_asistencia_alumno_fecha_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patologia',
            name='id_antecedente_medico',
        ),
    ]
