# Generated by Django 3.1 on 2020-10-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusoft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id_alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno',
            field=models.CharField(default='null', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=10),
        ),
    ]
