# Generated by Django 3.1 on 2020-10-31 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusoft', '0002_auto_20201031_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_adicionales',
            fields=[
                ('datos', models.AutoField(primary_key=True, serialize=False)),
                ('jubilacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10)),
                ('pension', models.CharField(choices=[('NACIONAL', 'NACIONAL'), ('PROVINCIAL', 'PROVINCIAL')], max_length=20)),
                ('cobertura_social', models.CharField(max_length=50)),
                ('certificado_discapacidad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50)),
                ('certificado_vigencia', models.DateField(null=True)),
                ('patologia', models.CharField(max_length=50)),
                ('patologias_asociadas', models.CharField(max_length=50)),
                ('nivel_educacional', models.CharField(max_length=50)),
                ('grupo_familiar', models.CharField(max_length=50)),
                ('actividades', models.CharField(max_length=50)),
                ('dias_actividades', models.CharField(max_length=100)),
                ('horario_actividades', models.CharField(max_length=50)),
                ('trabajo_madre', models.CharField(max_length=100)),
                ('trabajo_padre', models.CharField(max_length=100)),
                ('telefono_madre', models.CharField(max_length=50)),
                ('telefono_padre', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusoft.alumno')),
            ],
        ),
    ]
