# Generated by Django 3.1 on 2020-10-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusoft', '0003_datos_adicionales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
