# Generated by Django 3.1 on 2020-10-31 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusoft', '0004_auto_20201031_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='telefono_urgencia',
            fields=[
                ('tel_urgencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familiar', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusoft.alumno')),
            ],
        ),
    ]
