# Generated by Django 3.1 on 2020-10-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusoft', '0006_antecedente_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='autorizacion_medica',
            fields=[
                ('autorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=10)),
                ('dosis', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusoft.alumno')),
            ],
        ),
    ]
