# Generated by Django 3.1 on 2020-10-31 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusoft', '0007_autorizacion_medica'),
    ]

    operations = [
        migrations.CreateModel(
            name='acta_compromiso',
            fields=[
                ('compromiso', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.CharField(max_length=10)),
                ('ingreso', models.CharField(max_length=50)),
                ('salida', models.CharField(max_length=50)),
                ('traslado_alumno', models.CharField(max_length=50)),
                ('perzonas_autorizadas_retiro', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusoft.alumno')),
            ],
        ),
    ]
