# Generated by Django 3.2.8 on 2022-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('personal', '0002_auto_20210916_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_viaje', models.DateField()),
                ('gastos', models.CharField(max_length=50)),
                ('alumno', models.ManyToManyField(to='alumno.Alumno')),
                ('personal', models.ManyToManyField(to='personal.Personal')),
            ],
        ),
    ]
