# Generated by Django 3.2.8 on 2022-01-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0016_enfermeria_fecha_observacion'),
        ('personal', '0002_auto_20210916_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('edades', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inscripcion', models.DateField(null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_prestamo', models.DateField(null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.socio')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_devolucion', models.DateField(null=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamolibro')),
            ],
        ),
    ]
