# Generated by Django 3.2.8 on 2022-02-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_socio_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamolibro',
            name='libro',
        ),
        migrations.AddField(
            model_name='prestamolibro',
            name='libro',
            field=models.ManyToManyField(to='biblioteca.Libro'),
        ),
    ]
