# Generated by Django 3.2.8 on 2022-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20220211_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamolibro',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prestamolibro',
            name='fecha_de_devolucion',
            field=models.DateField(null=True),
        ),
    ]
