# Generated by Django 3.2.8 on 2022-03-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0002_auto_20220305_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperadora',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='cooperadora',
            name='salida',
        ),
    ]
