# Generated by Django 3.2.8 on 2022-03-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0004_auto_20220307_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperadora',
            old_name='salida',
            new_name='salidas',
        ),
    ]
