# Generated by Django 3.2.8 on 2022-03-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0005_rename_salida_cooperadora_salidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperadora',
            name='entradas',
        ),
        migrations.RemoveField(
            model_name='cooperadora',
            name='salidas',
        ),
    ]
