# Generated by Django 3.2.8 on 2022-03-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperadora', '0006_auto_20220307_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperadora',
            name='caja_chica',
            field=models.IntegerField(),
        ),
    ]
